// List of random words related to Apple spotlight
const words: Array<string> = [
  "App Store",
  "Keychain Access",
  "Activity Monitor",
  "Automator",
  "Audio MIDI setup",
  "Apple Inc.",
  "Bluetooth File Exchange",
  "Battery",
  "Google Chrome",
  "Chess",
  "Docker",
  "Dock and Menu",
  "Displays",
  "Dictionary",
  "Disk Utility",
  "Desktop and Screensaver",
  "Date & Time",
  "Finder",
  "Font Book",
  "FaceTime",
  "Family Sharing",
  "Google Chrome",
  "Grapher",
  "Home",
  "Help Viewer",
  "iTerm",
  "Image Capture",
  "iMovie",
  "Keynote",
  "Keyboard",
  "Launchpad",
  "Mail",
  "Messages",
  "Storage Management",
  "Maps",
  "Notes",
  "Numbers",
  "Network Utility",
  "Networks",
  "iOS App Installer",
  "Preview",
  "Photos",
  "Photo Booth",
  "QuickTime Player",
  "Reminders",
  "Recents",
  "System Preferences",
  "Safari",
  "Slack",
  "Siri",
];

export default words.sort();
